### ISSUE TITLE
无法启动-Game.java 数组越界

### ISSUE THREAD

**Issue by HugoRun** [icela/Castle-game#3]
文件 Castle-game/src/game/Game.java
变量 commandNames 的长度只有15,但是下面put了16次，导致出现异常

**Comment by lizhaohan001** [comment]
抱歉。。这个错误的原因是在commandNames中放置了新的命令(CommandTalk)而忘记删去老的lambda表达式造成的。
在我push后问题应该已经修复了。
（为什么我这会throw NPE？？为何您能够运行并看到数组越界的提示？？@HugoRun）

**Comment by ice1000** [comment]
谁说是你push之后修复的。。明明是我。。。（逃

**Comment by lizhaohan001** [comment]
？？？？@ice1000

**Comment by ice1000** [comment]
@lizhaohan001
https://github.com/icela/Castle-game/commit/e922b93a492d81b8ac32d59f4bc9f03c457763b1

**Comment by HugoRun** [comment]
@lizhaohan001 可能因为我是eclipse吧，真不晓得
